### ISSUE TITLE
NullReferenceException on TeamExplorerSectionBase.Initialize

### ISSUE THREAD

**Issue by MrLuje** [CDuke/AutoMerge#21]
Got this error every time since last update

![image](https://cloud.githubusercontent.com/assets/632075/11925734/d27f14b0-a7be-11e5-9236-70f32ce5b36e.png)

System.NullReferenceException: Object reference not set to an instance of an object.
   at System.Windows.Markup.WpfXamlLoader.TransformNodes(XamlReader xamlReader, XamlObjectWriter xamlWriter, Boolean onlyLoadOneNode, Boolean skipJournaledProperties, Boolean shouldPassLineNumberInfo, IXamlLineInfo xamlLineInfo, IXamlLineInfoConsumer xamlLineInfoConsumer, XamlContextStack`1 stack, IStyleConnector styleConnector)
   at System.Windows.Markup.WpfXamlLoader.Load(XamlReader xamlReader, IXamlObjectWriterFactory writerFactory, Boolean skipJournaledProperties, Object rootObject, XamlObjectWriterSettings settings, Uri baseUri)
   at System.Windows.Markup.WpfXamlLoader.LoadBaml(XamlReader xamlReader, Boolean skipJournaledProperties, Object rootObject, XamlAccessLevel accessLevel, Uri baseUri)
   at System.Windows.Markup.XamlReader.LoadBaml(Stream stream, ParserContext parserContext, Object parent, Boolean closeStream)
   at System.Windows.Application.LoadComponent(Object component, Uri resourceLocator)
   at AutoMerge.RecentChangesetsView.InitializeComponent()
   at AutoMerge.RecentChangesetsSection.CreateView(SectionInitializeEventArgs e)
   at Microsoft.TeamFoundation.Controls.WPF.TeamExplorer.TeamExplorerSectionBase.Initialize(Object sender, SectionInitializeEventArgs e)
   at AutoMerge.Base.TeamExplorerSectionBase.Initialize(Object sender, SectionInitializeEventArgs e)
   at Microsoft.TeamFoundation.Controls.WPF.TeamExplorer.Framework.TeamExplorerSectionHost.Initialize(Object context)

**Comment by CDuke** [comment]
Which Visual Studio version?

**Comment by MrLuje** [comment]
VS 2013 with Update 5

**Comment by CDuke** [comment]
Do you installed .Net Framework 4.6 or Visual Studio 2015?

**Comment by MrLuje** [comment]
Indeed, .Net Framework 4.6 is installed

**Comment by linowitsch** [comment]
Same error message on VS 2015 Enterprise Update 1, .Net-Framework 4.6.1 (+SDK)  + 4.5.1 (+SDK) + 4.5.2 + 4.6 are installed. 
The error occurs only sometimes.

**Comment by Mdsalman** [comment]
This problem is still there.
The plugin runs on the first try, but after closing and restarting VS2015 it gives the same error as posted by MrLuje.
Microsoft .Net Version 4.6.01055
VS 2015 Enterprise Update 1

**Comment by johannesprinz** [comment]
Same here:
Microsoft Visual Studio Enterprise 2015
Version 14.0.25422.01 Update 3
Microsoft .NET Framework
Version 4.6.01038

**Comment by linowitsch** [comment]
Issue occure only sometimes. Open multiple Instances of VS2015. Some are working, some not with this error. At the same time.

**Comment by rdevuser** [comment]
NullReferenceException occurs after installing Tag Admin in Visual Studio 2013 (https://visualstudiogallery.msdn.microsoft.com/3821cea9-96b4-46e3-9609-ad1d2c344424).  Uninstall and re-install Auto Merge did not affect the NullReferenceException.  Uninstall Tag Admin avoids the NullReferenceException.

System.NullReferenceException: Object reference not set to an instance of an object.
   at System.Windows.Markup.WpfXamlLoader.TransformNodes(XamlReader xamlReader, XamlObjectWriter xamlWriter, Boolean onlyLoadOneNode, Boolean skipJournaledProperties, Boolean shouldPassLineNumberInfo, IXamlLineInfo xamlLineInfo, IXamlLineInfoConsumer xamlLineInfoConsumer, XamlContextStack`1 stack, IStyleConnector styleConnector)
   at System.Windows.Markup.WpfXamlLoader.Load(XamlReader xamlReader, IXamlObjectWriterFactory writerFactory, Boolean skipJournaledProperties, Object rootObject, XamlObjectWriterSettings settings, Uri baseUri)
   at System.Windows.Markup.WpfXamlLoader.LoadBaml(XamlReader xamlReader, Boolean skipJournaledProperties, Object rootObject, XamlAccessLevel accessLevel, Uri baseUri)
   at System.Windows.Markup.XamlReader.LoadBaml(Stream stream, ParserContext parserContext, Object parent, Boolean closeStream)
   at System.Windows.Application.LoadComponent(Object component, Uri resourceLocator)
   at AutoMerge.RecentChangesetsView.InitializeComponent()
   at AutoMerge.RecentChangesetsSection.CreateView(SectionInitializeEventArgs e)
   at Microsoft.TeamFoundation.Controls.WPF.TeamExplorer.TeamExplorerSectionBase.Initialize(Object sender, SectionInitializeEventArgs e)
   at AutoMerge.Base.TeamExplorerSectionBase.Initialize(Object sender, SectionInitializeEventArgs e)
   at Microsoft.TeamFoundation.Controls.WPF.TeamExplorer.Framework.TeamExplorerSectionHost.Initialize(Object context)

System.NullReferenceException: Object reference not set to an instance of an object.
   at System.Windows.Markup.WpfXamlLoader.TransformNodes(XamlReader xamlReader, XamlObjectWriter xamlWriter, Boolean onlyLoadOneNode, Boolean skipJournaledProperties, Boolean shouldPassLineNumberInfo, IXamlLineInfo xamlLineInfo, IXamlLineInfoConsumer xamlLineInfoConsumer, XamlContextStack`1 stack, IStyleConnector styleConnector)
   at System.Windows.Markup.WpfXamlLoader.Load(XamlReader xamlReader, IXamlObjectWriterFactory writerFactory, Boolean skipJournaledProperties, Object rootObject, XamlObjectWriterSettings settings, Uri baseUri)
   at System.Windows.Markup.WpfXamlLoader.LoadBaml(XamlReader xamlReader, Boolean skipJournaledProperties, Object rootObject, XamlAccessLevel accessLevel, Uri baseUri)
   at System.Windows.Markup.XamlReader.LoadBaml(Stream stream, ParserContext parserContext, Object parent, Boolean closeStream)
   at System.Windows.Application.LoadComponent(Object component, Uri resourceLocator)
   at AutoMerge.BranchesView.InitializeComponent()
   at AutoMerge.BranchesSection.CreateView(SectionInitializeEventArgs e)
   at Microsoft.TeamFoundation.Controls.WPF.TeamExplorer.TeamExplorerSectionBase.Initialize(Object sender, SectionInitializeEventArgs e)
   at AutoMerge.Base.TeamExplorerSectionBase.Initialize(Object sender, SectionInitializeEventArgs e)
   at Microsoft.TeamFoundation.Controls.WPF.TeamExplorer.Framework.TeamExplorerSectionHost.Initialize(Object context)

**Comment by linowitsch** [comment]
The error occurs mainly if no solution has been loaded. 

With loading a small empty solution from somewhere I can make the extension work properly.
